CREATE TABLE IF NOT EXISTS logs (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nickname TEXT NOT NULL,
    note TEXT,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    user_id INTEGER REFERENCES users(id) NOT NULL
);

CREATE TYPE style_category AS ENUM (
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7'
);

CREATE TYPE color_category AS ENUM (
    'black',
    'brown',
    'green',
    'yellow',
    'gray',
    'red'
);

CREATE TYPE amount_category AS ENUM (
    'little',
    'normal',
    'a lot'
);

ALTER TABLE logs
    ADD COLUMN style style_category,
    ADD COLUMN color color_category,
    ADD COLUMN amount amount_category;
